apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: inventory-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: inventory-app
          # Denna tagg uppdateras av din GitHub Action
          image: ghcr.io/teehit101/inventory-tracker-app:a24ef6304e69e8b27d740d596ac7d993c53f2308
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              value: "inventorydb"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              value: "inventory_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: password
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
