apiVersion: external-secrets.io/v1
kind: ClusterSecretStore # <-- Ändra Kind!
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret-sa
            namespace: external-secrets # <-- Du måste berätta exakt var kontot bor!
