apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: inventory-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # Använd Longhorn i hemmalabbet
  resources:
    requests:
      storage: 2Gi
